apiVersion: v1
kind: Service
metadata:
  name: ad-service
  labels:
    app: ad-service
spec:
  selector:
    app: ad-service
  ports:
  - name: grpc
    port: 9555  
    targetPort: 9555
  type: ClusterIP
