apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels: 
    app: front-end
spec:
  type: LoadBalancer
  selector:
    app: front-end
  ports:
  - name: http
    port: 80
    targetPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: front-end-intenal
  labels: 
    app: front-end
spec:
  type: ClusterIP
  selector:
    app: front-end
  ports:
  - name: http
    port: 80
    targetPort: 8080