{{- with .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
data:
  {{- with .data }}
  PORT: "{{ .port }}"
  DISABLE_PROFILER: "{{ .disable_profiler }}"
  {{- end -}}
{{- end -}}