{{- with .Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .appName }}
  namespace: {{ $.Values.namespace}}
  labels:
    app: {{ .appName }}
spec:
  selector:
    matchLabels:
      app: {{ .appName }}
  template:
    metadata:
      labels:
        app: {{ .appName }}
    spec:
      serviceAccountName: {{ .serviceAccount }}
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      {{- with .container }}
      - name: {{ .containerName }}
        image: "{{ .image.name }}:{{ .image.tag }}"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: grpc
          containerPort: {{ .containerPort }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        envFrom:
        - configMapRef:
            name: {{ $.Values.configMap.name }}
        {{- with .probe }}
        readinessProbe:
          grpc:
            port: {{ .probePort }}
        livenessProbe:
          grpc:
            port: {{ .probePort }}
        {{- end -}}
      {{- end -}}
{{- end -}}
