apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog-service
spec:
  selector:
    matchLabels:
      app: productcatalog-service
  template:
    metadata:
      labels:
        app: productcatalog-service
    spec:
      serviceAccountName: productcatalog-service
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: productcatalog-service
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: "gnitin260/productcatalogservice:v1.0"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          grpc:
            port: 3550
        livenessProbe:
          grpc:
            port: 3550
