apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-service
  labels:
    app: currency-service
spec:
  selector:
    matchLabels:
      app: currency-service
  template:
    metadata:
      labels:
        app: currency-service
    spec:
      serviceAccountName: currency-service
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: currency-service
        image: "us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice:v0.10.2"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: grpc
          containerPort: 7000
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        envFrom:
        - configMapRef:
            name: currency-configmap
        readinessProbe:
          grpc:
            port: 7000
        livenessProbe:
          grpc:
            port: 7000
